# Generated by Django 3.1.3 on 2020-11-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('VideoId', models.AutoField(primary_key=True, serialize=False)),
                ('VideoLink', models.CharField(max_length=400)),
                ('VideoTimestamp', models.CharField(max_length=400)),
            ],
        ),
    ]
