# Generated by Django 3.1.3 on 2020-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliefapp', '0002_auto_20201127_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('BookmarkId', models.AutoField(primary_key=True, serialize=False)),
                ('BookmarkLink', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='VideoId',
            new_name='HistoryId',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='VideoLink',
            new_name='HistoryLink',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='VideoTimestamp',
            new_name='HistoryTimestamp',
        ),
    ]
